tasks:
  - name: Setup AWS CLI
    init: |
      # Install AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      # Optional: Verify that AWS CLI is configured correctly
      aws sts get-caller-identity

    command: python app.py
